In [2]:
import numpy as np
#1. Create a 3x3 NumPy Array with Random Integers Between 1 and 100, Then Interchange Rows and Columns
a = np.random.randint(1,100,(3,3))
a

array([[34,  2, 63],
       [28, 31, 76],
       [ 5, 99,  5]])

In [4]:
b = a.transpose()
b

array([[34, 28,  5],
       [ 2, 31, 99],
       [63, 76,  5]])

In [5]:
#2. Generate a 1D NumPy Array with 10 Elements, Reshape into 2x5, Then into 5x2

In [12]:
c = np.arange(46,56)
c.reshape(2,5)

array([[46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55]])

In [13]:
c.reshape(5,-7)

array([[46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55]])

In [14]:
#3. Create a 4x4 NumPy Array with Random Float Values, Add a Border of Zeros to Make it 6x6
a = np.random.rand(4,4)
a

array([[0.445804  , 0.48592089, 0.77497914, 0.43916926],
       [0.02570775, 0.17960144, 0.92026183, 0.18856233],
       [0.51296239, 0.163728  , 0.23874329, 0.3719121 ],
       [0.56364057, 0.63050473, 0.63202801, 0.07450687]])

In [15]:
b = np.pad(a, pad_width=1, mode='constant', constant_values=0)

In [16]:
b

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.445804  , 0.48592089, 0.77497914, 0.43916926,
        0.        ],
       [0.        , 0.02570775, 0.17960144, 0.92026183, 0.18856233,
        0.        ],
       [0.        , 0.51296239, 0.163728  , 0.23874329, 0.3719121 ,
        0.        ],
       [0.        , 0.56364057, 0.63050473, 0.63202801, 0.07450687,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [17]:
#4. Create an Array of Integers from 10 to 60 with a Step of 5

In [18]:
a = np.arange(10,60,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [19]:
#5. Create a NumPy Array of Strings and Apply Case Transformations

In [20]:
a = np.array(['python', 'numpy', 'java'])


upper_case = np.char.upper(a)
lower_case = np.char.lower(a)
title_case = np.char.title(a)
upper_case, lower_case, title_case

(array(['PYTHON', 'NUMPY', 'JAVA'], dtype='<U6'),
 array(['python', 'numpy', 'java'], dtype='<U6'),
 array(['Python', 'Numpy', 'Java'], dtype='<U6'))

In [21]:
#6. Generate a NumPy Array of Words and Insert a Space Between Each Character

In [22]:
a = np.array(['python', 'numpy', 'java'])
result = np.char.join(" ", a)
result

array(['p y t h o n', 'n u m p y', 'j a v a'], dtype='<U11')

In [23]:
#Perform Element-Wise Addition, Subtraction, Multiplication, and Division on Two 2D NumPy Arrays

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [25]:

add = array1 + array2

sub = array1 - array2

mult = array1 * array2

div = array1 / array2

In [27]:
add,sub,mult,div

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [28]:
#8. Create a 5x5 Identity Matrix and Extract Its Diagonal Elements

In [29]:
i = np.eye(5)
diagonal_elements = np.diag(i)
i,diagonal_elements

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

In [30]:
#9. Generate a NumPy Array of 100 Random Integers Between 0 and 1000 and Find All Prime Numbers

In [31]:

random_integers = np.random.randint(0, 1001, size=100)
print("Array of 100 Random Integers:\n", random_integers)

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

prime_numbers = np.array([num for num in random_integers if is_prime(num)])
print("\nPrime Numbers in the Array:\n", prime_numbers)


Array of 100 Random Integers:
 [256 462 162 983 457 995 251  22 885  39 974 789 684 475  34  85 275 999
 294   2 772 220 110 397 870 666 646 770 383 116 484 772 670 421 617 395
 222 577 418 460 251 762 847 450 564 339  34 278 300  71 324 225 860 581
 186 334 381 491  52 985 366 593 779 442  31 191 520 904 365 771 667 204
   3 892 284 458 442 835 123 599 521 984 193 561 472  66 376 973 180 179
 402 644 797 484 197 621 951 592 292 719]

Prime Numbers in the Array:
 [983 457 251   2 397 383 421 617 577 251  71 491 593  31 191   3 599 521
 193 179 797 197 719]


In [32]:
#10. Create a NumPy Array Representing Daily Temperatures for a Month and Calculate Weekly Averages

In [35]:
daily_temperatures = np.random.randint(20, 35, 30)

weekly_averages = []
for i in range(0, len(daily_temperatures), 7):
  week_temperatures = daily_temperatures[i: i + 7]
  weekly_averages.append(np.mean(week_temperatures))

weekly_averages = np.array(weekly_averages)
daily_temperatures,weekly_averages

(array([22, 32, 31, 29, 33, 21, 33, 26, 29, 24, 24, 32, 28, 22, 24, 22, 28,
        32, 22, 27, 28, 20, 24, 23, 29, 27, 30, 34, 33, 25]),
 array([28.71428571, 26.42857143, 26.14285714, 26.71428571, 29.        ]))